# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindows.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(513, 100)
        MainWindow.setMinimumSize(QtCore.QSize(513, 100))
        MainWindow.setMaximumSize(QtCore.QSize(513, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBoxJLinkSN = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxJLinkSN.setMinimumSize(QtCore.QSize(90, 28))
        self.comboBoxJLinkSN.setMaximumSize(QtCore.QSize(500, 28))
        self.comboBoxJLinkSN.setObjectName("comboBoxJLinkSN")
        self.horizontalLayout.addWidget(self.comboBoxJLinkSN)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEditDevice = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditDevice.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditDevice.setMaximumSize(QtCore.QSize(130, 30))
        self.lineEditDevice.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditDevice.setObjectName("lineEditDevice")
        self.horizontalLayout.addWidget(self.lineEditDevice)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEditStartAddress = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditStartAddress.setMinimumSize(QtCore.QSize(50, 30))
        self.lineEditStartAddress.setMaximumSize(QtCore.QSize(120, 30))
        self.lineEditStartAddress.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditStartAddress.setObjectName("lineEditStartAddress")
        self.horizontalLayout.addWidget(self.lineEditStartAddress)
        self.pushButtonStart = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonStart.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButtonStart.setAutoDefault(False)
        self.pushButtonStart.setDefault(False)
        self.pushButtonStart.setFlat(False)
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.horizontalLayout.addWidget(self.pushButtonStart)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 513, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionJLink = QtWidgets.QAction(MainWindow)
        self.actionJLink.setObjectName("actionJLink")
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionSaved = QtWidgets.QAction(MainWindow)
        self.actionSaved.setObjectName("actionSaved")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionRegister = QtWidgets.QAction(MainWindow)
        self.actionRegister.setObjectName("actionRegister")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAdvanced = QtWidgets.QAction(MainWindow)
        self.actionAdvanced.setObjectName("actionAdvanced")
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSaved)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuSetting.addAction(self.actionAdvanced)
        self.menuHelp.addAction(self.actionRegister)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JLinkTool"))
        self.label.setText(_translate("MainWindow", "JLink"))
        self.label_2.setText(_translate("MainWindow", "芯片型号"))
        self.lineEditDevice.setText(_translate("MainWindow", "STM32F407VE"))
        self.label_3.setText(_translate("MainWindow", "烧录地址"))
        self.lineEditStartAddress.setText(_translate("MainWindow", "0x08000000"))
        self.pushButtonStart.setText(_translate("MainWindow", "开始烧录"))
        self.pushButtonStart.setShortcut(_translate("MainWindow", "F5"))
        self.menuFile.setTitle(_translate("MainWindow", "文件(&F)"))
        self.menuSetting.setTitle(_translate("MainWindow", "设置(&S)"))
        self.menuHelp.setTitle(_translate("MainWindow", "帮助(&H)"))
        self.actionJLink.setText(_translate("MainWindow", "JLink设置"))
        self.actionImport.setText(_translate("MainWindow", "导入(&I)"))
        self.actionSaved.setText(_translate("MainWindow", "保存(&S)"))
        self.actionQuit.setText(_translate("MainWindow", "退出(&Q)"))
        self.actionRegister.setText(_translate("MainWindow", "注册(&R)"))
        self.actionAbout.setText(_translate("MainWindow", "关于(&A)"))
        self.actionAdvanced.setText(_translate("MainWindow", "高级设置"))


